<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/';

return array(
    'AL\\Forum\\' => array($typo3InstallDir . 'typo3conf/ext/forum/Classes'),
    'AlWebdesign\\Provider\\' => array($typo3InstallDir . 'typo3conf/ext/provider/Classes'),
    'B13\\Container\\' => array($typo3InstallDir . 'typo3conf/ext/container/Classes'),
    'Buepro\\ContainerElements\\' => array($typo3InstallDir . 'typo3conf/ext/container_elements/Classes'),
    'Buepro\\Pvh\\' => array($typo3InstallDir . 'typo3conf/ext/pvh/Classes'),
    'WapplerSystems\\WsScss\\' => array($typo3InstallDir . 'typo3conf/ext/ws_scss/Classes'),
);
